'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=x=>(x*100).toFixed(1)+'%',names={seoul:'서울',busan:'부경',jeju:'제주'},KEY='kra-predictions-v4';
let races=[],source=null,current=null,ranked=null,venue='seoul',odds={place:{},qpl:{}},manual=false,requestId=0;
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function start(r){const d=String(r.date||'').replaceAll('-','');return /^\d{8}$/.test(d)&&/^\d{2}:\d{2}$/.test(r.start_time||'')?Date.parse(`${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6,8)}T${r.start_time}:00+09:00`):NaN;}
function setVenue(v){venue=v;document.querySelectorAll('[data-venue]').forEach(b=>{b.classList.toggle('active',b.dataset.venue===v);b.setAttribute('aria-pressed',b.dataset.venue===v)});}
function records(){try{let a=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(a)?a:[]}catch{return []}}
function put(a){try{localStorage.setItem(KEY,JSON.stringify(a));return true}catch{$('#saveStatus').textContent='기기에 저장하지 못했습니다. 브라우저 저장 공간을 확인하세요.';return false}}
function timingReasons(r){const why=[];if(!Number.isFinite(start(r)))why.push('출발 시각 확인 필요');else if(start(r)<=Date.now())why.push('이미 출발한 경주');if(!manual&&(!source?.updated_at||Date.now()-Date.parse(source.updated_at)>30*60000||!Number.isFinite(Date.parse(source.updated_at))))why.push('갱신 후 30분 경과 · 최신 출전정보 확인 필요');return why;}
function why(r,x,type){return [...candidateReasons(r,x,type),...timingReasons(r),...(manual?['직접 입력 / 데모']:[])];}
function pickHTML(x,r,type,lead=false){if(!x)return '<p class="hint">후보 없음</p>';const reasons=why(r,x,type),name=x.names.map(esc).join(' · '),num=x.numbers.join(' – ');if(!lead)return `<div class="candidate"><span><b>${num}</b> ${name}${x.odds?`<br>${x.odds}배 · 추정 EV ${pct(x.ev)}`:''}</span><strong>${pct(x.prob)}</strong></div>`;return `<div class="status ${reasons.length?'hold':''}">${reasons.length?'추천 보류':'검토 후보'}</div><div class="lead-number">${num}</div><p class="lead-name">${name}</p><div class="prob"><small>추정 ${type==='place'?'입상':'동반입상'}</small>${pct(x.prob)}</div><p class="hint">${reasons.length?esc(reasons.join(' · ')):'데이터 충실도 '+Math.round(x.quality*100)+'% · 실적 검증 전'}</p>${x.odds?`<p class="hint">${x.odds}배 · 추정 EV ${pct(x.ev)}</p>`:''}`;}
function render(){if(!current)return;ranked=analyze(current,$('#mode').value,odds);const r=ranked;$('#analysis').hidden=false;$('#raceTitle').textContent=(names[r.venue]||r.venue_name||'직접 입력')+' '+r.race_no+'R';$('#raceMeta').textContent=[r.date,r.title,manual?'직접 입력 / 데모':''].filter(Boolean).join(' · ');$('#horseCount').textContent=r.horses.length+'두';$('#placeRule').textContent=r.k+'착 이내';$('#modeHelp').textContent=r.mode==='accuracy'?'추정 적중확률 순으로 추천합니다. 배당을 입력해도 순위는 바뀌지 않습니다.':'배당을 입력한 후보를 추정 기대수익률 순으로 정렬합니다. 적중확률은 낮아질 수 있습니다.';const warning=timingReasons(r);$('#raceWarning').hidden=!warning.length;$('#raceWarning').textContent=warning.join(' · ');$('#placeLead').innerHTML=pickHTML(r.places[0],r,'place',true);$('#pairLead').innerHTML=pickHTML(r.pairs[0],r,'pair',true);$('#placeList').innerHTML=r.places.slice(1,5).map(x=>pickHTML(x,r,'place')).join('');$('#pairList').innerHTML=r.pairs.slice(1,5).map(x=>pickHTML(x,r,'pair')).join('');$('#horses').innerHTML=r.horses.map(h=>`<div class="horse"><strong>${h.number} ${esc(h.name)} · ${pct(h.prob)}</strong><p class="hint">${h.reasons.map(esc).join(' · ')}</p><p class="hint">레이팅 ${esc(h.rating??'—')} · 부담 ${esc(h.burden??'—')}kg · 마체중 ${esc(h.horse_weight??'미발표')} · 데이터 ${Math.round(h.quality*100)}%</p></div>`).join('');$('#savePrediction').disabled=manual||!Number.isFinite(start(r))||start(r)<=Date.now()||warning.length>0;}
function select(r,isManual=false){current=r;manual=isManual;odds={place:{},qpl:{}};$('#placeOdds').value='';$('#pairOdds').value='';if(names[r.venue])setVenue(r.venue);const d=String(r.date||'');if(/^\d{8}$/.test(d))$('#date').value=d.slice(0,4)+'-'+d.slice(4,6)+'-'+d.slice(6,8);if(r.race_no)$('#raceNo').value=r.race_no;$('#saveStatus').textContent='경주·추천 기준별 최초 기록을 보존합니다.';render();}
async function load(){const id=++requestId;$('#dataStatus').textContent='경주 정보를 확인하는 중…';try{const res=await fetch('data/latest.json?t='+Date.now(),{cache:'no-store'});if(!res.ok)throw Error('HTTP '+res.status);const doc=await res.json();if(!Array.isArray(doc.races))throw Error('데이터 형식 오류');if(id!==requestId)return false;source=doc;races=doc.races;$('#dataStatus').textContent=`갱신 ${doc.updated_at?.replace('T',' ').slice(0,16)||'시각 미확인'} · ${races.length}개 경주`;return true}catch(e){if(id===requestId)$('#dataStatus').textContent='불러오기 실패 · 경주 보기를 눌러 다시 시도하세요.';return false}}
function parseOdds(text,pair){const out={};if(!text.trim())return out;for(const cell of text.split(',')){const m=cell.trim().match(pair?/^(\d+)-(\d+)\s*=\s*(\d+(?:\.\d+)?)$/:/^(\d+)\s*=\s*(\d+(?:\.\d+)?)$/);if(!m)throw Error('배당 형식을 확인하세요. 예: '+(pair?'2-7=3.4':'2=1.5'));const nums=pair?[+m[1],+m[2]]:[+m[1]],v=+(pair?m[3]:m[2]);if(v<1||!Number.isFinite(v)||new Set(nums).size!==nums.length||nums.some(n=>!ranked.horses.some(h=>+h.number===n)))throw Error('출전 마번과 1배 이상 배당을 입력하세요.');out[nums.sort((a,b)=>a-b).join('-')]=v;}return out;}
function save(){render();if($('#savePrediction').disabled)return;const r=ranked,key=[r.date,r.venue,r.race_no,r.mode].join(':');let all=records();if(all.some(x=>x.id===key)){$('#saveStatus').textContent='이미 기록한 경주입니다. 최초 추천을 유지합니다.';return}const copy=(x,t)=>({numbers:x.numbers,prob:x.prob,held:why(r,x,t).length>0});all.push({id:key,date:r.date,venue:r.venue,race:r.race_no,mode:r.mode,model:r.model,saved:new Date().toISOString(),start:start(r),k:r.k,field:r.horses.map(h=>+h.number),place:copy(r.places[0],'place'),pair:copy(r.pairs[0],'pair'),result:null});if(put(all)){$('#saveStatus').textContent='기록했습니다. 경주 후 공식 결과를 입력하세요.';renderHistory();}}
function stat(all,type,mode){const eligible=all.filter(x=>x.mode===mode&&!x[type].held),done=eligible.filter(x=>x.result),hit=done.filter(x=>x.result[type+'Hit']).length,paid=done.filter(x=>!x.result[type+'Hit']||x.result[type+'Odds']!=null),returns=paid.reduce((s,x)=>s+(x.result[type+'Hit']?x.result[type+'Odds']:0),0);return `<div class="stat">${type==='place'?'연승':'복연승'} · ${mode==='accuracy'?'적중률 우선':'수익성'}<b>${done.length?pct(hit/done.length):'—'}</b>${hit}/${done.length} 적중 · 대기 ${eligible.length-done.length}<br>환수율 ${paid.length?pct(returns/paid.length):'—'} (${paid.length}건)</div>`;}
function renderHistory(){const all=records();$('#stats').innerHTML=['accuracy','value'].flatMap(m=>['place','pair'].map(t=>stat(all,t,m))).join('');$('#history').innerHTML=all.length?[...all].reverse().map(x=>`<details class="record"><summary>${esc(names[x.venue]||x.venue)} ${esc(x.date)} ${x.race}R · ${x.mode==='accuracy'?'적중률':'수익성'} ${x.result?'· 결과 입력됨':''}</summary><p>연승 ${x.place.numbers.join('-')}${x.place.held?' (보류)':''} / 복연승 ${x.pair.numbers.join('-')}${x.pair.held?' (보류)':''}</p><p>${esc(x.saved.replace('T',' ').slice(0,19))} UTC 저장 · 모델 ${esc(x.model)}</p>${x.result?`<p>공식 착순 ${x.result.finish.join(' → ')} · 연승 ${x.result.placeHit?'적중':'미적중'} / 복연승 ${x.result.pairHit?'적중':'미적중'}</p>`:''}<form data-record="${esc(x.id)}"><label>공식 1·2·3착 마번<input name="finish" required placeholder="예: 2,7,4" value="${x.result?.finish.join(',')||''}"></label><label>공식 연승 입상 마번 (취소로 기준이 바뀐 경우 수정)<input name="placeWinners" required placeholder="예: 2,7,4" value="${x.result?.placeWinners.join(',')||''}"></label><div class="result-fields"><label>추천 연승의 확정 배당<input name="placeOdds" type="number" min="1" step="0.01" placeholder="적중 시 입력" value="${x.result?.placeOdds??''}"></label><label>추천 복연승의 확정 배당<input name="pairOdds" type="number" min="1" step="0.01" placeholder="적중 시 입력" value="${x.result?.pairOdds??''}"></label></div><p class="hint">마사회 확정 결과를 확인해 입력하세요. 동착·환불 경주는 입력하지 마세요.</p><button type="submit" ${Date.now()<x.start?'disabled':''}>${x.result?'결과 수정':'결과 저장'}</button></form></details>`).join(''):'<p class="hint">아직 기록이 없습니다. 경주 전에 추천을 기록해 보세요.</p>';}
$('#history').addEventListener('submit',e=>{e.preventDefault();try{const f=e.target,all=records(),x=all.find(v=>v.id===f.dataset.record);if(!x||Date.now()<x.start)throw Error('경주 시작 후 입력할 수 있습니다.');const nums=v=>v.trim().split(/[,\s]+/).map(Number),finish=nums(f.elements.finish.value),pw=nums(f.elements.placeWinners.value);for(const a of [finish,pw])if(a.some(n=>!x.field.includes(n))||new Set(a).size!==a.length)throw Error('기록된 출전마의 서로 다른 마번을 입력하세요.');if(finish.length!==3||![2,3].includes(pw.length)||pw.some((n,i)=>n!==finish[i]))throw Error('착순 3두와 공식 연승 입상마 2~3두를 착순대로 입력하세요.');const odd=v=>v===''?null:Number(v),po=odd(f.elements.placeOdds.value),qo=odd(f.elements.pairOdds.value);if([po,qo].some(v=>v!==null&&(!Number.isFinite(v)||v<1)))throw Error('배당은 1 이상으로 입력하세요.');x.result={finish,placeWinners:pw,placeHit:pw.includes(x.place.numbers[0]),pairHit:x.pair.numbers.every(n=>finish.includes(n)),placeOdds:po,pairOdds:qo,entered:new Date().toISOString()};if(put(all))renderHistory();}catch(err){alert(err.message)}});
$('#date').value=day();for(let i=1;i<=16;i++)$('#raceNo').insertAdjacentHTML('beforeend',`<option value="${i}">${i}R</option>`);
document.querySelectorAll('[data-venue]').forEach(b=>b.onclick=()=>{setVenue(b.dataset.venue);showSelected();});function showSelected(){const r=races.find(x=>x.venue===venue&&String(x.date)===$('#date').value.replaceAll('-','')&&+x.race_no===+$('#raceNo').value);if(r)select(r);else{current=null;ranked=null;$('#analysis').hidden=true;$('#dataStatus').textContent='선택한 경주 데이터가 없습니다. 날짜나 경주를 바꿔주세요.';}}
$('#date').onchange=showSelected;$('#raceNo').onchange=showSelected;$('#loadBtn').onclick=async()=>{if(await load())showSelected()};$('#nextBtn').onclick=async()=>{if(!await load())return;const future=races.filter(x=>x.venue===venue&&start(x)>Date.now()).sort((a,b)=>start(a)-start(b));if(future[0])select(future[0]);else $('#dataStatus').textContent='선택 경마장의 예정 경주가 없습니다.';};$('#mode').onchange=render;$('#applyOdds').onclick=()=>{try{const next={place:parseOdds($('#placeOdds').value,false),qpl:parseOdds($('#pairOdds').value,true)};odds=next;render()}catch(e){alert(e.message)}};$('#savePrediction').onclick=save;$('#manualBtn').onclick=()=>{try{const r=JSON.parse($('#manualJson').value);analyze(r);select(r,true)}catch(e){alert('출전마 JSON을 확인하세요. '+e.message)}};
$('#demoBtn').onclick=()=>select({venue,date:day().replaceAll('-',''),race_no:1,title:'데모 · 실제 경주 아님',horses:Array.from({length:8},(_,i)=>({number:i+1,name:'샘플 '+(i+1),rating:50-i*2,burden:54,starts_1y:10,wins_1y:i<2?2:0,seconds_1y:2,thirds_1y:1,distance_starts:5,distance_top3:i<3?3:1,recent_finishes:[i+1,3,5],jockey_stats_1y:{place_rate:.3},trainer_stats_1y:{place_rate:.25},horse_weight:480}))},true);
$('#lockBtn').onclick=()=>{$('#lockScreen').hidden=false;$('#pinInput').focus()};$('#unlockBtn').onclick=()=>{if($('#pinInput').value==='1234'){$('#lockScreen').hidden=true;$('#pinInput').value='';$('#lockError').textContent=''}else $('#lockError').textContent='PIN이 다릅니다.';};
renderHistory();load().then(ok=>{if(!ok)return;const future=races.filter(x=>start(x)>Date.now()).sort((a,b)=>start(a)-start(b));if(future[0])select(future[0]);else showSelected()});
